# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 27, 18, 10, 41, 681000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
