# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='foto',
            new_name='image',
        ),
    ]
