# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20160227_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='art',
            new_name='content',
        ),
    ]
