# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='theme',
            field=models.CharField(default=0, max_length=10, verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
