# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_public_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 16, 29, 0, 252690), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='public',
            name='theme',
            field=models.CharField(max_length=20, verbose_name='Тема'),
        ),
    ]
