# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20160307_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='text',
            field=models.TextField(default='Введите текст статьи', max_length=10000, verbose_name='Текст публикации'),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 16, 32, 36, 105036), verbose_name='Дата публикации'),
        ),
    ]
