# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 13:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20160307_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 16, 33, 58, 414744), verbose_name='Дата публикации'),
        ),
    ]
