# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20160307_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 17, 2, 35, 648964), verbose_name='Дата публикации'),
        ),
    ]
