# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 10:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20160308_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 13, 28, 44, 197747), verbose_name='Дата публикации'),
        ),
    ]
