# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_auto_20160308_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='image',
        ),
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 13, 35, 52, 239230), verbose_name='Дата публикации'),
        ),
    ]
