# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 10:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_auto_20160308_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='image',
            field=models.FileField(blank=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 13, 40, 37, 882568), verbose_name='Дата публикации'),
        ),
    ]
