# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_auto_20160308_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 11, 14, 25, 46, 583789), verbose_name='Дата публикации'),
        ),
    ]
