# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_auto_20160314_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 0, 46, 15, 747), verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_public',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Public'),
        ),
    ]
