# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 23:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_auto_20160315_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(verbose_name='Добавить комментарий'),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 2, 59, 41, 583697), verbose_name='Дата публикации'),
        ),
    ]
