# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0019_auto_20160315_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 10, 59, 55, 781080), verbose_name='Дата публикации'),
        ),
    ]
