# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0022_auto_20160315_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 11, 37, 34, 629279), verbose_name='Дата публикации'),
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comm',
        ),
    ]
