# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 08:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0024_auto_20160315_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments_public',
        ),
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 11, 45, 50, 373634), verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
