# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 08:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0025_auto_20160315_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 15, 11, 57, 25, 783409), verbose_name='Дата публикации'),
        ),
    ]
