# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 22:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0034_auto_20160331_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='users_dislikes',
            field=models.ForeignKey(default=datetime.datetime(2016, 3, 31, 22, 8, 17, 553000, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='public',
            name='users_likes',
            field=models.ForeignKey(default=datetime.datetime(2016, 3, 31, 22, 8, 24, 77000, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='public',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 1, 1, 7, 53, 527000), verbose_name=b'\xd0\x94\xd0\xb0\xd1\x82\xd0\xb0 \xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='public',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
